FROM python:3.7.15
RUN DEBIAN_FRONTEND=noninteractive && apt-get -y update && apt-get -y install build-essential openjdk-11-jdk zip unzip wget
RUN wget https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-dist.zip
RUN mkdir bazel-5.3.2 && unzip -d ./bazel-5.3.2 bazel-5.3.2-dist.zip
WORKDIR /bazel-5.3.2
RUN env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh && cp output/bazel /usr/local/bin
