FROM python:3.7.15 as tf-build
COPY --from=bazel:3.7 /usr/local/bin/bazel /usr/local/bin
#RUN apt-get -y install git
#RUN git clone https://github.com/tensorflow/tensorflow
#WORKDIR /tensorflow
#RUN git checkout r2.7
#ENV TF_NEED_CUDA=0 \
#TF_NEED_TENSORRT=0 \
#PYTHON_BIN_PATH="/usr/local/bin/python" \
#USE_DEFAULT_PYTHON_LIB_PATH=1 \
#TF_NEED_ROCM=0 \
#CC_OPT_FLAGS="-Wno-sign-compare" \
#TF_DOWNLOAD_CLANG=0 \
#TF_SET_ANDROID_WORKSPACE=0
#RUN ./configure
#RUN bazel build --config=opt -c opt //tensorflow/tools/pip_package:build_pip_package
#RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
RUN touch /tmp/tensorflow_pkg/tensorflow-test.whl

FROM python:3.7.15 as tf-install
COPY --from=tf-build /tmp/tensorflow_pkg/*.whl wheels/
#RUN pip install /wheels/tensorflow-*.whl
#RUN curl https://raw.githubusercontent.com/keras-team/keras-io/master/examples/vision/mnist_convnet.py > test.py
#RUN python test.py

CMD ["python"]
