ARG PYTHON_VERSION

FROM python:$PYTHON_VERSION as tfx-build
ARG MINOR_VERSION
COPY --from=bazel:4.2 /usr/local/bin/bazel /usr/local/bin
RUN apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install git openjdk-11-jdk

RUN pip install numpy
RUN mkdir /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/tfx-bsl.git
WORKDIR /tfx/tfx-bsl
RUN if [ "$MINOR_VERSION" = "x" ] ; then git checkout r1.4.0 ; else git checkout tags/v1.4.$MINOR_VERSION ; fi
COPY replace_commits.sh ./
RUN chmod +x replace_commits.sh
RUN ./replace_commits.sh && python setup.py bdist_wheel && cp dist/*.whl /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/data-validation.git
WORKDIR /tfx/data-validation
RUN if [ "$MINOR_VERSION" = "x" ] ; then git checkout r1.4.0 ; else git checkout tags/v1.4.$MINOR_VERSION ; fi
COPY WORKSPACE ./
RUN python setup.py bdist_wheel && cp dist/*.whl /wheels


#FROM python:$PYTHON_VERSION as tfx-install
#COPY --from=tfx-build /wheels/*.whl wheels/
#RUN pip install /wheels/*.whl
#RUN curl https://gist.githubusercontent.com/kennysong/b9f3ffe1299d331cdde92c46504a5ea1/raw/832b6a958dec86ce313d5be3033e281a87c21847/taxi_2020_test_converted.csv > taxi.csv
#RUN python -c "import tensorflow_data_validation as tfdv; tfdv.generate_statistics_from_csv('taxi.csv')"
#
#CMD ["python"]
