ARG PYTHON_VERSION

FROM python:$PYTHON_VERSION as tfx-build
ARG MINOR_VERSION
COPY --from=bazel:4.2 /usr/local/bin/bazel /usr/local/bin
RUN DEBIAN_FRONTEND=noninteractive && apt-get -y update && apt-get -y install git openjdk-11-jdk
RUN pip install numpy && mkdir /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/tfx-bsl.git
WORKDIR /tfx/tfx-bsl
RUN if [ "$MINOR_VERSION" = "x" ] ; then git checkout r1.5.0 ; else git checkout tags/v1.5.$MINOR_VERSION ; fi
COPY helpers/replace_commits.sh ./
RUN chmod +x replace_commits.sh && ./replace_commits.sh && python setup.py bdist_wheel && cp dist/*.whl /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/data-validation.git
WORKDIR /tfx/data-validation
RUN if [ "$MINOR_VERSION" = "x" ] ; then git checkout r1.5.0 ; else git checkout tags/v1.5.$MINOR_VERSION ; fi
COPY helpers/WORKSPACE ./
RUN python setup.py bdist_wheel && cp dist/*.whl /wheels
