FROM python:3.7.15 as tfx-build
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential openjdk-11-jdk zip unzip wget
RUN wget https://github.com/bazelbuild/bazel/releases/download/4.2.3/bazel-4.2.3-dist.zip
RUN mkdir bazel-4.2.3
RUN unzip -d ./bazel-4.2.3 bazel-4.2.3-dist.zip
WORKDIR /bazel-4.2.3
RUN env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
RUN cp output/bazel /usr/local/bin

RUN apt-get -y install git

RUN pip install numpy
RUN mkdir /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/tfx-bsl.git
WORKDIR /tfx/tfx-bsl
RUN git checkout r1.8.0
RUN sed -i 's/e1d388e7e74803050423d035e4374131b9b57919/215105818dfde3174fe799600bb0f3cae233d0bf/g' WORKSPACE
RUN sed -i 's/baebd1536bec56ae7d7c060c20c01af89ecba2c0b1bc8992b652520655395f94/b4e20d9e752a75c10636675691b1e9c2698e0764cb404987d0ffa77223041c19/g' WORKSPACE
RUN python setup.py bdist_wheel
RUN cp dist/*.whl /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/data-validation.git
WORKDIR /tfx/data-validation
RUN git checkout r1.8.0
RUN python setup.py bdist_wheel
RUN cp dist/*.whl /wheels


FROM python:3.7.15 as tfx-install
COPY --from=tfx-build /wheels/*.whl wheels/
RUN pip install /wheels/*.whl
FROM python:3.7.15 as tf-build
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential openjdk-11-jdk zip unzip wget
RUN wget https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-dist.zip
RUN mkdir bazel-5.3.2
RUN unzip -d ./bazel-5.3.2 bazel-5.3.2-dist.zip
WORKDIR /bazel-5.3.2
RUN env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
RUN cp output/bazel /usr/local/bin

WORKDIR /

RUN apt-get -y install git

RUN git clone https://github.com/tensorflow/tensorflow
WORKDIR /tensorflow
RUN git checkout r2.9

ENV PYTHONUNBUFFERED=1
RUN pip install -U pip six 'numpy<1.19.0' wheel setuptools mock 'future>=0.17.1'
RUN pip install -U keras_applications --no-deps
RUN pip install -U keras_preprocessing --no-deps
ENV TF_NEED_CUDA 0
ENV TF_NEED_TENSORRT 0
ENV PYTHON_BIN_PATH "/usr/local/bin/python"
ENV USE_DEFAULT_PYTHON_LIB_PATH 1
ENV TF_NEED_ROCM 0
ENV CC_OPT_FLAGS "-Wno-sign-compare"
ENV TF_DOWNLOAD_CLANG 0
ENV TF_SET_ANDROID_WORKSPACE 0
RUN ./configure
RUN bazel build --config=opt -c opt //tensorflow/tools/pip_package:build_pip_package
RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

FROM python:3.7.15 as tf-install
COPY --from=tf-build /tmp/tensorflow_pkg/*.whl wheels/
RUN pip install /wheels/tensorflow-*.whl
RUN curl https://raw.githubusercontent.com/keras-team/keras-io/master/examples/vision/mnist_convnet.py > test.py
RUN python test.py

CMD ["python"]
