ARG PYTHON_VERSION

FROM python:$PYTHON_VERSION as tfx-build
ARG MINOR_VERSION
COPY --from=bazel:4.2 /usr/local/bin/bazel /usr/local/bin
RUN apt-get -y install git

RUN pip install numpy
RUN mkdir /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/tfx-bsl.git
WORKDIR /tfx/tfx-bsl
RUN if [ "$MINOR_VERSION" = "x"] ; then git checkout r1.9.0 ; else git checkout tags/v1.9.$MINOR_VERSION ; fi
COPY replace_commits.sh ./
RUN ./replace_commits.sh && python setup.py bdist_wheel && cp dist/*.whl /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/data-validation.git
WORKDIR /tfx/data-validation
RUN if [ "$MINOR_VERSION" = "x" ] ; then git checkout r1.9.0 ; else git checkout tags/v1.9.$MINOR_VERSION ; fi
RUN python setup.py bdist_wheel && cp dist/*.whl /wheels
