FROM python:3.8.15 as tfx-build
COPY --from=bazel:4.2 /usr/local/bin/bazel /usr/local/bin
RUN apt-get -y install git

RUN pip install numpy
RUN mkdir /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/tfx-bsl.git
WORKDIR /tfx/tfx-bsl
RUN git checkout r1.9.0
RUN sed -i 's/e1d388e7e74803050423d035e4374131b9b57919/215105818dfde3174fe799600bb0f3cae233d0bf/g' WORKSPACE
RUN sed -i 's/baebd1536bec56ae7d7c060c20c01af89ecba2c0b1bc8992b652520655395f94/b4e20d9e752a75c10636675691b1e9c2698e0764cb404987d0ffa77223041c19/g' WORKSPACE
RUN python setup.py bdist_wheel
RUN cp dist/*.whl /wheels

WORKDIR /tfx
RUN git clone https://github.com/tensorflow/data-validation.git
WORKDIR /tfx/data-validation
RUN git checkout r1.9.0
RUN python setup.py bdist_wheel
RUN cp dist/*.whl /wheels


FROM python:3.8.15 as tfx-install
COPY --from=tfx-build /wheels/*.whl wheels/
RUN pip install /wheels/*.whl
RUN python -c "import tensorflow_data_validation as tfdv; print('TFDV version:', tfdv.version.__version__)"

CMD ["python"]
