FROM python:3.7.15 as tfx-build
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential openjdk-11-jdk zip unzip wget
RUN wget https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-dist.zip
RUN mkdir bazel-5.3.2
RUN unzip -d ./bazel-5.3.2 bazel-5.3.2-dist.zip
WORKDIR /bazel-5.3.2
RUN env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
RUN cp output/bazel /usr/local/bin

RUN apt-get -y install git

WORKDIR /tfx
RUN wget https://zlib.net/zlib-1.2.13.tar.gz
RUN tar -xf zlib-1.2.13.tar.gz
WORKDIR /tfx/zlib-1.2.13/
RUN ./configure
RUN make
RUN make install
WORKDIR /tfx
RUN git clone https://github.com/tensorflow/data-validation.git
WORKDIR /tfx/data-validation
RUN git checkout r1.5.0
RUN pip install numpy
CMD ["python"]
#RUN python setup.py bdist_wheel
#
#
#FROM python:3.7.15 as tfx-install
#COPY --from=tfx-build /tfx/dist/*.whl wheels/
#RUN pip install /wheels/*.whl
#RUN python -c "import tensorflow_data_validation as tfdv; print('TFDV version:', tfdv.version.__version__)"
#
#CMD ["python"]
